/**
 * Pre-build script: bundle the copy-paste components (packages/vibekit/components)
 * into src/components/bundled.ts, so `vibekit add <name>` needs no network.
 * The manifest names each component's files; the same files feed the docs.
 *
 * Run with: bun run bundle-components
 */
import { readFile } from 'fs/promises'
import { join } from 'path'

const DIR = Bun.fileURLToPath(new URL('../../../packages/vibekit/components', import.meta.url))

const manifest = JSON.parse(await readFile(join(DIR, 'manifest.json'), 'utf-8')) as Record<
  string,
  { files: string[]; description: string }
>
const components = []
for (const [name, entry] of Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))) {
  const files = []
  for (const path of entry.files) files.push({ path, content: await readFile(join(DIR, path), 'utf-8') })
  components.push({ name, description: entry.description, files })
}
const out = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: bun run bundle-components
// Source: packages/vibekit/components

import type { BundledComponent } from './index.js'

export const BUNDLED_COMPONENTS: BundledComponent[] = ${JSON.stringify(components, null, 2)}
`
await Bun.write(new URL('../src/components/bundled.ts', import.meta.url), out)
console.log(`Bundled ${components.length} components: ${components.map((c) => c.name).join(', ')}`)
