/**
 * Pre-build script: bundle the repo's canonical skills (skills/ at the
 * monorepo root) into src/skills/bundled.ts. No network — skills are
 * versioned with the CLI and reviewed like code.
 *
 * Run with: bun run bundle-skills
 */

import { readdir, readFile } from 'fs/promises'
import { join, relative } from 'path'

const SKILLS_DIR = Bun.fileURLToPath(new URL('../../../skills', import.meta.url))

interface SkillFile {
  path: string
  content: string
}

interface SkillDirectory {
  name: string
  files: SkillFile[]
}

async function readSkill(dir: string): Promise<SkillFile[]> {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true })
  const files: SkillFile[] = []
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) continue
    const fullPath = join(entry.parentPath, entry.name)
    files.push({
      path: relative(dir, fullPath),
      content: await readFile(fullPath, 'utf-8'),
    })
  }
  return files.sort((a, b) => a.path.localeCompare(b.path))
}

async function main() {
  const entries = await readdir(SKILLS_DIR, { withFileTypes: true })
  const skills: SkillDirectory[] = []

  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) continue
    const files = await readSkill(join(SKILLS_DIR, entry.name))
    if (files.length > 0) {
      skills.push({ name: entry.name, files })
    }
  }

  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: bun run bundle-skills
// Source: skills/ at the monorepo root

import type { SkillDirectory } from './index.js'

export const BUNDLED_SKILLS: SkillDirectory[] = ${JSON.stringify(skills, null, 2)}
`

  const outputPath = Bun.fileURLToPath(new URL('../src/skills/bundled.ts', import.meta.url))
  await Bun.write(outputPath, output)
  console.log(`Bundled ${skills.length} skills from ${SKILLS_DIR}`)
  for (const skill of skills) console.log(`  ${skill.name} (${skill.files.length} files)`)
}

main().catch((error) => {
  console.error('Failed to bundle skills:', error)
  process.exit(1)
})
