/**
 * Pre-build script to fetch skills from GitHub and generate bundled.ts
 *
 * Run with: bun run bundle-skills
 *
 * Set GITHUB_TOKEN environment variable to avoid rate limits:
 *   GITHUB_TOKEN=ghp_xxx bun run scripts/bundle-skills.ts
 *
 * This eliminates GitHub API rate limit issues by bundling skills at build time
 * instead of fetching them at runtime during `vibekit init`.
 */

const SKILLS_REPO = 'algorand-devrel/algorand-agent-skills'
const SKILLS_PATH = 'skills'
const SKILLS_REF = 'main'

const GITHUB_TOKEN = process.env.GITHUB_TOKEN

function getHeaders(): HeadersInit {
  const headers: HeadersInit = {
    Accept: 'application/vnd.github.v3+json',
    'User-Agent': 'vibekit-bundle-skills',
  }
  if (GITHUB_TOKEN) {
    headers['Authorization'] = `Bearer ${GITHUB_TOKEN}`
  }
  return headers
}

interface SkillFile {
  path: string
  content: string
}

interface SkillDirectory {
  name: string
  files: SkillFile[]
}

interface GitHubContentItem {
  name: string
  path: string
  type: 'file' | 'dir'
  url: string
  download_url: string | null
}

/**
 * Recursively fetch all markdown files from a skill directory
 */
async function fetchSkillFiles(dirUrl: string, basePath = ''): Promise<SkillFile[]> {
  const response = await fetch(dirUrl, { headers: getHeaders() })

  if (!response.ok) {
    throw new Error(`Failed to fetch skill directory: ${response.status}`)
  }

  const items: GitHubContentItem[] = await response.json()
  const files: SkillFile[] = []

  for (const item of items) {
    if (item.type === 'dir') {
      // Recursively fetch subdirectory files
      const subPath = basePath ? `${basePath}/${item.name}` : item.name
      const subFiles = await fetchSkillFiles(item.url, subPath)
      files.push(...subFiles)
    } else if (item.type === 'file' && item.name.endsWith('.md') && item.download_url) {
      // Fetch markdown file content
      const contentResponse = await fetch(item.download_url, { headers: getHeaders() })

      if (!contentResponse.ok) {
        console.warn(`Failed to fetch ${item.path}: ${contentResponse.status}`)
        continue
      }

      const content = await contentResponse.text()
      const filePath = basePath ? `${basePath}/${item.name}` : item.name

      files.push({
        path: filePath,
        content,
      })
    }
  }

  return files
}

/**
 * Fetch skills from the GitHub repository
 */
async function fetchSkillsFromGitHub(): Promise<SkillDirectory[]> {
  const apiUrl = `https://api.github.com/repos/${SKILLS_REPO}/contents/${SKILLS_PATH}?ref=${SKILLS_REF}`

  const response = await fetch(apiUrl, { headers: getHeaders() })

  if (!response.ok) {
    throw new Error(`Failed to fetch skills directory: ${response.status} ${response.statusText}`)
  }

  const skillDirs: GitHubContentItem[] = await response.json()
  const skills: SkillDirectory[] = []

  for (const dir of skillDirs) {
    if (dir.type !== 'dir') continue

    const skillFiles = await fetchSkillFiles(dir.url)
    if (skillFiles.length > 0) {
      skills.push({
        name: dir.name,
        files: skillFiles,
      })
    }
  }

  return skills
}

async function main() {
  console.log('Fetching skills from GitHub...')
  console.log(`  Repository: ${SKILLS_REPO}`)
  console.log(`  Path: ${SKILLS_PATH}`)
  console.log(`  Ref: ${SKILLS_REF}`)
  console.log(`  Auth: ${GITHUB_TOKEN ? 'Using GITHUB_TOKEN' : 'No token (may hit rate limits)'}`)
  console.log('')

  const skills = await fetchSkillsFromGitHub()

  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: bun run scripts/bundle-skills.ts
// Source: https://github.com/${SKILLS_REPO}

import type { SkillDirectory } from '../../types'

export const BUNDLED_SKILLS: SkillDirectory[] = ${JSON.stringify(skills, null, 2)}

export const BUNDLED_AT = '${new Date().toISOString()}'
`

  const outputPath = Bun.fileURLToPath(new URL('../src/lib/skills/bundled.ts', import.meta.url))
  await Bun.write(outputPath, output)

  console.log(`Bundled ${skills.length} skills to src/lib/skills/bundled.ts`)
  console.log(`Generated at: ${new Date().toISOString()}`)
}

main().catch((error) => {
  console.error('Failed to bundle skills:', error)
  process.exit(1)
})
