/**
 * Pre-build script: fetch skills from GitHub and generate src/skills/bundled.ts.
 *
 * Run with: bun run bundle-skills
 * Set GITHUB_TOKEN to avoid rate limits.
 */

const SKILLS_REPO = 'algorand-devrel/algorand-agent-skills'
const SKILLS_PATH = 'skills'
const SKILLS_REF = 'main'

const GITHUB_TOKEN = process.env.GITHUB_TOKEN

function getHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    Accept: 'application/vnd.github.v3+json',
    'User-Agent': 'vibekit-bundle-skills',
  }
  if (GITHUB_TOKEN) {
    headers['Authorization'] = `Bearer ${GITHUB_TOKEN}`
  }
  return headers
}

interface SkillFile {
  path: string
  content: string
}

interface SkillDirectory {
  name: string
  files: SkillFile[]
}

interface GitHubContentItem {
  name: string
  path: string
  type: 'file' | 'dir'
  url: string
  download_url: string | null
}

async function fetchSkillFiles(dirUrl: string, basePath = ''): Promise<SkillFile[]> {
  const response = await fetch(dirUrl, { headers: getHeaders() })
  if (!response.ok) {
    throw new Error(`Failed to fetch skill directory: ${response.status}`)
  }

  const items = (await response.json()) as GitHubContentItem[]
  const files: SkillFile[] = []

  for (const item of items) {
    if (item.type === 'dir') {
      const subPath = basePath ? `${basePath}/${item.name}` : item.name
      files.push(...(await fetchSkillFiles(item.url, subPath)))
    } else if (item.type === 'file' && item.name.endsWith('.md') && item.download_url) {
      const contentResponse = await fetch(item.download_url, { headers: getHeaders() })
      if (!contentResponse.ok) {
        console.warn(`Failed to fetch ${item.path}: ${contentResponse.status}`)
        continue
      }
      const content = await contentResponse.text()
      files.push({ path: basePath ? `${basePath}/${item.name}` : item.name, content })
    }
  }

  return files
}

async function fetchSkillsFromGitHub(): Promise<SkillDirectory[]> {
  const apiUrl = `https://api.github.com/repos/${SKILLS_REPO}/contents/${SKILLS_PATH}?ref=${SKILLS_REF}`
  const response = await fetch(apiUrl, { headers: getHeaders() })
  if (!response.ok) {
    throw new Error(`Failed to fetch skills directory: ${response.status} ${response.statusText}`)
  }

  const skillDirs = (await response.json()) as GitHubContentItem[]
  const skills: SkillDirectory[] = []

  for (const dir of skillDirs) {
    if (dir.type !== 'dir') continue
    const skillFiles = await fetchSkillFiles(dir.url)
    if (skillFiles.length > 0) {
      skills.push({ name: dir.name, files: skillFiles })
    }
  }

  return skills
}

async function main() {
  console.log(`Fetching skills from ${SKILLS_REPO}@${SKILLS_REF}/${SKILLS_PATH} ...`)
  const skills = await fetchSkillsFromGitHub()

  const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: bun run scripts/bundle-skills.ts
// Source: https://github.com/${SKILLS_REPO}

import type { SkillDirectory } from './index.js'

export const BUNDLED_SKILLS: SkillDirectory[] = ${JSON.stringify(skills, null, 2)}
`

  const outputPath = Bun.fileURLToPath(new URL('../src/skills/bundled.ts', import.meta.url))
  await Bun.write(outputPath, output)
  console.log(`Bundled ${skills.length} skills to src/skills/bundled.ts`)
}

main().catch((error) => {
  console.error('Failed to bundle skills:', error)
  process.exit(1)
})
