/**
 * Generates the tools reference from the tool contract: every query and
 * action, its description, and its parameters. Never hand-edit the output.
 *
 *   bun packages/vibekit/scripts/generate-reference.ts
 */
import { z } from 'zod'

import { isAction, type AnyTool } from '../src/core/index.js'
import { defaultPlugins, defaultQueries, defaultActions } from '../src/preset/index.js'

const OUT = new URL('../../../apps/website/src/content/docs/docs/reference/tools.md', import.meta.url)

type Schema = { properties?: Record<string, { type?: string | string[]; description?: string; enum?: unknown[] }>; required?: string[] }

function params(tool: AnyTool): string {
  const schema = z.toJSONSchema(tool.parameters) as Schema
  const entries = Object.entries(schema.properties ?? {})
  if (entries.length === 0) return '_No parameters._'
  const rows = entries.map(([name, prop]) => {
    const type = prop.enum ? prop.enum.map((v) => `\`${String(v)}\``).join(' \\| ') : Array.isArray(prop.type) ? prop.type.join(' \\| ') : (prop.type ?? 'object')
    const required = schema.required?.includes(name) ? 'yes' : ''
    return `| \`${name}\` | ${type} | ${required} | ${(prop.description ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')} |`
  })
  return ['| parameter | type | required | description |', '| --- | --- | --- | --- |', ...rows].join('\n')
}

function section(title: string, tools: AnyTool[]): string {
  return [`## ${title}`, '', ...tools.map((tool) => [`### \`${tool.name}\``, '', tool.description, '', params(tool), ''].join('\n'))].join('\n')
}

const plugins = defaultPlugins()
const body = [
  '---',
  'title: Tools',
  'description: Every query and action in @initlabs/vibekit, generated from the tool contract.',
  '---',
  '',
  '<!-- GENERATED by packages/vibekit/scripts/generate-reference.ts — do not edit. -->',
  '',
  'A **query** reads; nothing leaves the process. An **action** drafts a transaction group that a human approves and a wallet signs; in compose mode it returns the unsigned group. Every tool is callable the same way from MCP, the agent, `vibekit tool <name>`, and `POST /tools/<name>`.',
  '',
  section(`Queries (${defaultQueries.length})`, defaultQueries),
  section(`Actions (${defaultActions.length})`, defaultActions),
  ...plugins.map((plugin) => section(`Plugin: ${plugin.name} (${plugin.tools.length})${plugin.description ? ` — ${plugin.description}` : ''}`, plugin.tools.filter((t) => !isAction(t)).concat(plugin.tools.filter(isAction)))),
].join('\n')
await Bun.write(OUT, body)
console.log(`wrote ${OUT.pathname}: ${defaultQueries.length} queries, ${defaultActions.length} actions, ${plugins.length} plugins`)
